### ISSUE TITLE
issue when run 

### ISSUE THREAD

**Issue by mohyM** [aqeelanwar/SocialDistancingAI#17]
/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from network_model import model
  File "/Users/userName/Downloads/master/test_distance/SocialDistancingAI-dependabot-pip-tensorflow-1.15.2/network_model.py", line 5, in <module>
    import backbone
  File "/Users/userName/Downloads/master/test_distance/SocialDistancingAI-dependabot-pip-tensorflow-1.15.2/backbone.py", line 6, in <module>
    import tensorflow as tf
  File "/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 35, in <module>
    from tensorflow._api.v1 import compat
  File "/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorflow/_api/v1/compat/__init__.py", line 22, in <module>
    from tensorflow._api.v1.compat import v2
  File "/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorflow/_api/v1/compat/v2/__init__.py", line 303, in <module>
    from tensorboard.summary._tf import summary
  File "/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorboard/summary/__init__.py", line 25, in <module>
    from tensorboard.summary import v1
  File "/Users/userName/opt/anaconda3/lib/python3.7/site-packages/tensorboard/summary/v1.py", line 46, in <module>
    pr_curve_pb = _pr_curve_summary.pb
AttributeError: module 'tensorboard.plugins.pr_curve.summary' has no attribute 'pb'

**Comment by Ash-intosh** [comment]
I faced the same difficulty some days ago. Try using tensorflow 1.13.2.
Hope this will work for you.
